# This compose file stands up a basic instance of Open QuarterMaster.
# More information available here: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/main/deployment/Compose/README.md
#
version: '3.8'

# Define the internal network
networks:
  oqm_internal:
    driver: bridge

services:
  mongo:
    image: docker.io/mongo:${MONGO_IMAGE_TAG}
    container_name: oqm-infra-mongo
    restart: ${SYS_RESTART}
    networks:
      - oqm_internal
    volumes:
      # Mounts the container's internal data directory to a named volume
      - ${SYS_DATA_DIR}/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      # This will create the database immediately upon startup
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ping: 1}).ok" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  postgres:
    image: docker.io/postgres:${POSTGRES_IMAGE_TAG}
    container_name: oqm-infra-postgres
    restart: ${SYS_RESTART}
    networks:
      - oqm_internal
    volumes:
      # Mounts the container's internal data directory to a named volume
      - ${SYS_DATA_DIR}/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # This will create the database immediately upon startup
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG}
    container_name: oqm-infra-keycloak
    restart: ${SYS_RESTART}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - oqm_internal
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ${KEYCLOAK_REALM_FILE}:/opt/keycloak/data/import/oqm-realm.json
    command: start --import-realm
    environment:
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: [ "CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
  core-api:
    image: docker.io/ebprod/oqm-core-api:${CORE_API_PORT_IMAGE_TAG}
    container_name: oqm-core-api
    restart: ${SYS_RESTART}
    depends_on:
      mongo:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - oqm_internal
    ports:
      - "${CORE_API_PORT}:80"
    environment:
      "smallrye.jwt.verify.key.location": http://oqm-infra-keycloak:8080/realms/oqm/protocol/openid-connect/certs
      QUARKUS_MONGODB_CONNECTION-STRING: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@oqm-infra-mongo:27017
      QUARKUS_MONGODB_DATABASE: ${MONGO_DATABASE}
      "mp.messaging.outgoing.events-outgoing.enabled": "false"
    healthcheck:
      test: [ "CMD-SHELL", "{ printf 'HEAD /q/health HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/80" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    
  core-base_station:
    image: docker.io/ebprod/oqm-core-base_station:${CORE_BASE_STATION_IMAGE_TAG}
    container_name: oqm-core-base_station
    restart: ${SYS_RESTART}
    depends_on:
      core-api:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    network_mode: host
    environment:
      QUARKUS_HTTP_PORT: ${CORE_BASE_STATION_PORT}
      QUARKUS_OIDC_CLIENT-ID: ${CORE_BASE_STATION_CLIENT}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${CORE_BASE_STATION_CLIENT_SECRET}
      QUARKUS_OIDC_AUTH-SERVER-URL: http://localhost:${KEYCLOAK_PORT}/realms/oqm
      OQM_CORE_API_BASEURI: http://localhost:${CORE_API_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "{ printf 'HEAD /q/health HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/80" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
